### ISSUE TITLE
[BUG] unable to connect to worker: invalid data found in the buffer (possible echo): exit status 1

### ISSUE THREAD

**Issue by beanhacker** [spiral/roadrunner#339] opened 2020-06-10 09:40 UTC
C:\Users\yanyouwei\Downloads\roadrunner-1.8.1-windows-amd64\roadrunner-1.8.1-windows-amd64>rr -c rr.yaml -v serve
DEBU[0000] [metrics]: disabled
DEBU[0000] [headers]: disabled
DEBU[0000] [static]: disabled
DEBU[0000] [health]: disabled
DEBU[0000] [reload]: disabled
DEBU[0000] [rpc]: started
DEBU[0000] [http]: started
ERRO[0000] [http]: [http]: unable to connect to worker: invalid data found in the buffer (possible echo): exit status 1
DEBU[0000] [rpc]: stopped
Error: [http]: unable to connect to worker: invalid data found in the buffer (possible echo): exit status 1

setting[yy.yaml] as below:
http:
  address:         0.0.0.0:8080
  workers.command: "php worker.php"

**Comment by wolfy-j** [comment] 2020-06-10 09:46
Hi,

this error caused by incorrect worker configuration, broken PHP process, or echo in STDOUT. Please check the Troubleshooting section - https://roadrunner.dev/docs/php-worker

**Comment by 48d90782** [comment] 2020-06-10 09:49
#329

**Comment by wolfy-j** [comment] 2020-06-10 09:54
I do not think they are connected since we already patched protocol. Didn't we?

**Comment by 48d90782** [comment] 2020-06-10 09:55
Yup, we reverted changes, but debugging wasn't started yet :disappointed: I just stacking issues with a similar problem.

**Comment by 48d90782** [comment] 2020-07-06 10:04
@beanhacker Hey, please, try to update RR to 1.8.2?

**Comment by 48d90782** [comment] 2020-08-27 08:01
@beanhacker I am going to close this issue since the same problem was fixed in the 1.8.2 release.

**Closed by 48d90782** 2020-08-27 08:01 UTC
Labels: F-need-verification, R-question
