### ISSUE TITLE
[BUG] why the builded binary can not run directly?

### ISSUE THREAD

**Issue by beanhacker** [spiral/roadrunner#534] opened 2021-02-07 06:29 UTC
run: 
     rr.exe serve
    use config i copyed(.rr.yaml):
          http: address: 0.0.0.0:8080
          workers.command: "php worker.php"

error: 
2021/02/07 14:24:48 handle_serve_command: Init error:
        endure_initialize:
        endure_add_edges:
        endure_add_init_deps:
        endure_add_interface_dep: can't find dependency: logger.Logger for the vertex: memcached.Plugin

suggest:
     i have try this ispired package for a period of time, no one successed. can you build one exe with a ready config to run directly when download your binary? go's spirit is simple and simple, but yours not imple this.

thanks.

**Comment by 48d90782** [comment] 2021-02-07 09:56
Hey @beanhacker. Nice to meet you. Thanks for the report and sorry for the bad UX. At the moment RR2 in the beta stage, so, there are expected to be some bugs inside :)
If I understood correctly, you tried to run RR2 with the following configuration:
```yaml
http:
    address: 0.0.0.0:8080
    
workers.command: "php worker.php"
```
You have to rewrite this config to be compatible with RR2:
```yaml
http:
    address: 0.0.0.0:8080
server:
    command: "php worker.php"
logs:
    level: [debug,info,warning,panic] <---- choose the level you need
```

I found a bug in the endure interfaces resolving mechanism. And that's why you get this error:
`endure_add_interface_dep: can't find dependency: logger.Logger for the vertex: memcached.Plugin`
Also, `logs` is a mandatory field in the `.rr.yaml` RR2 config. We will definitely cover this in the documentation. Please, stay tuned and wait for the next beta release.

**Comment by wolfy-j** [comment] 2021-02-08 12:02
The answer: we have changed the config for RR2 and it's not 100% compatible with RR1.

**Comment by beanhacker** [comment] 2021-02-08 12:08
@48d90782  thanks, solved it.
but a new question is: we need php rel package also when use roadrunner? can not put it all in one roadrunner?
nginx && apache do the same thing as roadrunner now. what we feel bad is that php need to be deployed with 3rd server.
so i think roadrunner want to solve this problem. do i understand wrong?

**Comment by wolfy-j** [comment] 2021-02-11 14:20
Can you re-phrase your question? PHP package for RR provides easier, PSR compatible abstraction for PHP only. But the general point for RR is to replace nginx+php-fpm pair or apache.

RoadRunner does not work via default stateful SAPI (dying model) of PHP which is the core root of its performance benefits.

**Comment by 48d90782** [comment] 2021-02-12 08:51
@beanhacker Reported bug was resolved. Could you please verify that and if everything is good, close this issue?

**Comment by 48d90782** [comment] 2021-02-14 22:03
@beanhacker I'm going to close this issue. Feel free to re-open it if the problem is still exists.

**Closed by 48d90782** 2021-02-14 22:03 UTC
Labels: B-bug, B-regression
