### ISSUE TITLE
[BUG, RR1] Prometheus exporter ignores internalErrorCode for rr_http_request_total

### ISSUE THREAD

**Issue by hugochinchilla** [spiral/roadrunner#602] opened 2021-03-18 15:28 UTC
If you use `internalErrorCode` this is not taken into account when incrementing the `rr_http_request_total` counter.

I tried this code:

```
http:
  internalErrorCode: 503
```
Create a slow controller that sleeps for some time, set workers to a low number, allocateTimeout also should be quite low, use bombardier to saturate the server, you need to force roadrunner to produce errors because it can't allocate workers.

Then look at the metrics exporter, you will see something like this:

```
rr_http_request_total{status="500"} 389
```

I would expect to see:

```
rr_http_request_total{status="503"} 389
```

**Comment by hugochinchilla** [comment] 2021-03-18 15:30
tested on 1.9.2, I haven't had the opportunity to try 2.0, I'm waiting for https://github.com/Baldinof/roadrunner-bundle/issues/29 to upgrade

**Comment by 48d90782** [comment] 2021-03-18 15:56
@hugochinchilla metrics service from the RR 1.9.2 uses its own HTTP server. This error code likely comes from it, but not from the HTTP service.

**Comment by 48d90782** [comment] 2021-03-18 16:02
To clarify, there are several HTTP servers that are responsible for the services (plugins in the RR2). The HTTP service in the RR1 responsible for the HTTP requests has its own server, but requests to the `metrics` service are handled by the integrated into the `metric` service HTTP server.

**Comment by hugochinchilla** [comment] 2021-03-18 16:51
I think I did not explain this well so I will focus on way I want to achieve instead of a possible solution.

I want to be able to read from prometheus how frequently I'm leaving requests unattended because I don't have available runners.

I did not found a metric for that and thought that maybe I would be able to identify those errors by the status code. So I see two possible solutions:

 * Create a new metric that increments for errored requests (internal errors, not application errors).
 * Increment `rr_http_request_total` using the real status code that was used for the response instead of using 500 for internal errors.

**Comment by 48d90782** [comment] 2021-03-19 07:13
> I think I did not explain this well so I will focus on what I want to achieve instead of on a possible solution.
> 
> I want to be able to read from prometheus how frequently I'm leaving requests unattended because I don't have available workers.
> 
> I did not found a metric for that and thought that maybe I would be able to identify those errors by the status code. So I see two possible solutions:
> 
> * Create a new metric that increments for errored requests (internal errors, not application errors).
> * Increment `rr_http_request_total` using the real status code that was used for the response instead of using 500 for internal errors.
> 
> Edited: some errors.

@hugochinchilla It will be better to move this proposal to a separate ticket and close this one since the original description does not relate to the proposal. You can put a reference to this ticket in a new one. Thank you for the proposal.

**Comment by hugochinchilla** [comment] 2021-03-19 07:30
@48d90782 I'm not sure, don't you think is a bug not using the same status code for the actual response and for the response status counter? 

I could create a new feature request for having a new counter just for the internal errors, but still, If i'm getting 503 errors on the client side I would expect to see the counter reflect that.

**Comment by 48d90782** [comment] 2021-03-19 07:33
> @48d90782 I'm not sure, don't you think is a bug not using the same status code for the actual response and for the response status counter?

This is not a bug, just a different behavior since these services use the different HTTP servers inside.

>I could create a new feature request for having a new counter just for the internal errors, but still, If i'm getting 503 errors on the client side I would expect to see the counter reflect that.

Yes, please, create a new feature request to add shared internal error codes and a new counter.

**Comment by hugochinchilla** [comment] 2021-03-19 07:45
@48d90782 I think you are focusing to much in a detail implementation. Does it really matter if there are multiple http servers? as a user I just care of it doing the expected thing.

I found where the problem originates. It's not just a matter of reading the configuration object and using the `internalErrorCode` value instead of hardcoding the status?

```
        #cmd/rr/http/metrics.go

	case rrhttp.EventError:
		e := ctx.(*rrhttp.ErrorEvent)

		c.requestCounter.With(prometheus.Labels{
			"status": "500",
		}).Inc()

		c.requestDuration.With(prometheus.Labels{
			"status": "500",
		}).Observe(e.Elapsed().Seconds())
	}
```

I agree that adding a new counter should be another feature request though.

**Comment by hugochinchilla** [comment] 2021-03-19 07:46
If for some architectural decision the metrics server should not be reading config from the http block then the http server could pass that value in the ErrorEvent.

**Comment by 48d90782** [comment] 2021-03-19 07:59
> @48d90782 I think you are focusing to much in a detail implementation. Does it really matter if there are multiple http servers? as a user I just care of it doing the expected thing.

I just try to be on the same page with you and give you an understanding of the internal behavior. For sure, as for the end-user that does not matter, a user sees a bug that leads to the bad UX and that is the problem.

The metrics service should not lay on the HTTP section, because obviously, it can be empty. I am thinking to move all HTTP codes stuff to a different configuration section, thus all HTTP servers inside RR can inherit the same behavior.

I understand your point and your problem, and I will try to help you ASAP. But the original issue was about the bug, which actually isn't a bug. Thus, will be great if you create a new feature request to create a new counter and inherit the same HTTP error codes for the whole app. Thank you for understanding 😃.

**Closed** 2021-03-19 09:48 UTC
Labels: B-bug, F-need-verification
