### ISSUE TITLE
rpc unix socket is not closed sometimes

### ISSUE THREAD

**Issue by Richard87** [spiral/roadrunner#19] opened 2018-06-22 12:37 UTC
There is some issues with the shutdown procedures, when using either STDOUT/IN or Unix socket it doesn't close it, and then it can't start properly later (I havent tried a TCP socket yet).

```
./rr serve -v -d
DEBU[0000] [rpc]: started                               
DEBU[0000] [http]: started                              
DEBU[0000] [static]: started                            
ERRO[0000] [rpc]: listen unix ./var/roadrunner2.sock: bind: address already in use 
DEBU[0000] [http]: stopped                              
ERRO[0000] [http]: listen unix ./var/roadrunner2.sock: bind: address already in use 
^C%                                                                                   
```

**Comment by wolfy-j** [comment] 2018-06-22 12:51
Can you post your .rr file here?

**Comment by Richard87** [comment] 2018-06-22 12:55
Hi!

some changes (I was slightly confused by the different listen directives for rpc and listen...:

```
# rpc bus allows php application and external clients to talk to rr services.
rpc:
  # enable rpc server
  enable: true

  # rpc connection DSN. Supported TCP and Unix sockets.
  # listen: tcp://127.0.0.1:6001
  listen: unix://./var/roadrunner3.sock

# http service configuration.
http:
  # set to false to disable http server.
  enable:     true

  # http host to listen.
  address:    0.0.0.0:8000

  # max POST request size, including file uploads in MB.
  maxRequest: 200

  # file upload configuration.
  uploads:
    # list of file extensions which are forbidden for uploading.
    forbid: [".php", ".exe", ".bat"]

  # http worker pool configuration.
  workers:
    # php worker command.
    command:  "php psr-worker.php"

    # connection method (pipes, tcp://:9000, unix://socket.unix).
    relay:    "pipes"

    # worker pool configuration.
    pool:
      # number of workers to be serving.
      numWorkers: 4

      # maximum jobs per worker, 0 - unlimited.
      maxJobs:  0

      # for how long pool should attempt to allocate free worker (request timeout). Nanoseconds atm. (60s)
      allocateTimeout: 60000000000

      # amount of time given to worker to gracefully destruct itself. Nanoseconds atm. (30s)
      destroyTimeout:  30000000000

# static file serving.
static:
  # serve http static files
  enable:  true

  # root directory for static file (http would not serve .php and .htaccess files).
  dir:   "web"

  # list of extensions to forbid for serving.
  forbid: [".php", ".htaccess", "package.json", "yarn.lock"]
```

(Also, executing `./rr http:workers` never completes, I have a feeling it's related ;) )

**Comment by Richard87** [comment] 2018-06-22 15:22
I added `xdebug_break()` the the psr_worker.php (inside the loop), and it crashed.

After I start it again, all logging seems to be going strong, but nothing works:
![image](https://user-images.githubusercontent.com/5749715/41784694-c49a95b0-7640-11e8-82c0-20d1ed250ca4.png)
![image](https://user-images.githubusercontent.com/5749715/41784711-cceccdc8-7640-11e8-9582-1757a73f9257.png)

**Comment by wolfy-j** [comment] 2018-06-22 19:01
That's weird, I'm unable to reproduce such issue on the similar machine, can you check if this port is being listened by anything `netstat -ant`?

Do you see any workers when you try to to run `rr http:workers` command? Have you tried to connect to your workes over unix socket?

**Comment by wolfy-j** [comment] 2018-06-23 17:50
Fixed in recent version.

**Closed by wolfy-j** 2018-06-23 17:50 UTC
Labels: bug
