### ISSUE TITLE
[BUG] http:reset seems not working

### ISSUE THREAD

**Issue by ghost** [spiral/roadrunner#314] opened 2020-04-29 02:27 UTC
roadrunner 1.7.1

background:
1, laravel 7.8.1 with https://github.com/avto-dev/roadrunner-laravel integration
2, roadrunner rpc enabled.
3, 
opcache.enable => On => On
opcache.enable_cli => Off => Off
4, systemd unit file
```
[Unit]
Description=High-performance PHP application server

[Service]
Type=simple
ExecStart=/usr/local/bin/rr serve -c /xxx/.rr.yaml
ExecReload=/usr/local/bin/rr http:reset -c /xxx/.rr.yaml
Restart=always
RestartSec=30
User=www-data
[Install]
WantedBy=default.target
```
4, systemctl reload rr.service,  success
5, ./rr  -c .rr.yaml http:workers. all workers are "created x seconds ago"
6, new code doesn't work.
~~7, systemctl restart rr.service, new code works~~
7, stop first and and re-serve to make new code works
`/usr/local/bin/rr stop -c /xxx/.rr.yaml; /usr/local/bin/rr serve -c /xxx/.rr.yaml `

Please let me know if you need anything else.

**Comment by wppd** [comment] 2020-04-29 02:36
here is my rr.yaml
```
rpc:
  enable: true
  listen: tcp://127.0.0.1:18081
gzip:
  enable: true
reload:
  enable: false
http:
  address:   0.0.0.0:8081
  # in MB
  maxRequestSize: 5000
  uploads:
    forbid: [".php", ".exe", ".bat"]
  workers:
    command:  "php ./vendor/bin/rr-worker"
    pool:
      #it'll use the number of cpu processors
      #numWorkers: 4
      maxJobs:  10
      allocateTimeout: 60
      destroyTimeout:  60

static:
  dir:   "public"
  forbid: [".php", ".htaccess"]

limit:
  # check worker state each second
  interval: 2

  # custom watch configuration for each service
  services:
    # monitor http workers
    http:
      # maximum allowed memory consumption per worker (soft)
      maxMemory: 1024

      # maximum time to live for the worker (soft)
      TTL: 0

      # maximum allowed amount of time worker can spend in idle before being removed (for weak db connections, soft)
      idleTTL: 0

      # max_execution_time (brutal)
      execTTL: 300

```
when reload: true, its working as expected, no need to call http:reset. I don't really want to use reload in production. thanks

**Comment by wppd** [comment] 2020-04-29 13:09
it's so weird. I can't reproduce this problem...
one more thing to add is that, I'm using deployphp/deployer to deploy code.
the file structure is
```
symlink: current -> releases/26
folder: releases
```
so the complete serve command is `/usr/local/bin/rr serve -c /xxx/current/.rr.yaml`

once the code was deployed, I invoked 

`/usr/local/bin/rr -c /xxx/current/.rr.yaml http:reset`

but the new code didn't work. 

Right now, I change code (some wordings) on the same production server (with same rr.yaml pasted above), the change works without rr reload...

**Comment by 48d90782** [comment] 2020-04-29 13:27
@wppd np, thanks for the comments. A little bit later I'll try to reproduce your problem with provided scenarious.

**Comment by wppd** [comment] 2020-04-30 14:16
uh... it's so confusing..  it happens again. 
I've done two deployments. 
in each deployment, new code still not working. manually trigger http:reset twice and same thing. gotta restart rr to make new code works.

it's hard to reproduce. @48d90782 if you need anything, I'd be happy to provide!

**Comment by klkvsk** [comment] 2020-08-24 17:17
This is due to that symlink resolving only once at rr startup. 

You start with `-c .../current/.rr.yaml`, rr resolves working dir to `releases/26` and keeps it in memory. Even after you point `current` to `releases/27`, it still starts new workers in 26th.  Calling `http:reset` doesn't help here, as it only respawns workers, it does not reload configuration and pathes.

I use same way of deploying with current-symlink switch, and it's impossible to do such releases without complete restart.

**Comment by 48d90782** [comment] 2020-08-24 17:33
Sorry for the delay. @klkvsk you are right. Config structure will be placed in memory, so, `http:reset` will not reload it. The only way to reload config in such case is to restart the roadrunner.

**Comment by klkvsk** [comment] 2020-08-24 17:44
Opened a feature request about this: #350

**Comment by rustatian** [comment] 2021-06-12 14:47
Closing this. #350 will be tracking ticket for the issue.

**Closed by rustatian** 2021-06-12 14:47 UTC
Labels: F-need-verification, O-linux
