### ISSUE TITLE
[BUG] Problem with http:reset

### ISSUE THREAD

**Issue by Alexfilus** [spiral/roadrunner#266] opened 2020-03-04 08:02 UTC
Gitlab CI pipeline ended with that:
`$ ./rr http:reset
 Restarting http worker pool: Error: unexpected EOF
 ERROR: Job failed: exit status 1`
Site was not worked about a minute (502 response), and after that just started automatically.

**Comment by 48d90782** [comment] 2020-03-04 08:11
@Alexfilus Could you please post the link to the related GitlabCI pipeline? And what site wasn't worked?

**Comment by wolfy-j** [comment] 2020-03-04 08:22
Sounds like the http:reset can’t connect to the server. Make sure to specify the correct config for rpc. Was it working before?

**Comment by wolfy-j** [comment] 2020-03-04 08:22
Also, can you share roadrunner logs?

**Comment by Alexfilus** [comment] 2020-03-04 09:09
Next deploy finished by that: 
> $ ./rr http:reset
 Error: dial tcp 127.0.0.1:6001: connect: connection refused
 ERROR: Job failed: exit status 1

Only the first one pipeline worked successful. 

Where can I see RR logs?

**Comment by wolfy-j** [comment] 2020-03-04 09:10
Do you have rr server running? You can only reset already running server.

**Comment by Alexfilus** [comment] 2020-03-04 09:12
> @Alexfilus Could you please post the link to the related GitlabCI pipeline? Which web site didn't work?

I can't show the code. Project isn't opensource, but I can say, it is Laravel based.

**Comment by Alexfilus** [comment] 2020-03-04 09:15
> Do you have rr server running? You can only reset already running server.
Yes. Looks like pm2 keeps it running.
And I see 68 restarts since this morning... May be are they conflicting?

**Comment by Alexfilus** [comment] 2020-03-04 09:28
On another server everything works fine, but RR keep running by systemd.

**Comment by wolfy-j** [comment] 2020-03-07 14:31
Your pipeline does not have access to running instance of RR. This is not the server issue but rather a configuration of your env. 

I will close this issue since it's is not a bug and I can't help debugging it without seeing your configuration. If you'll have more details please post here.

**Closed by wolfy-j** 2020-03-07 14:31 UTC
Labels: F-insufficent details
