### ISSUE TITLE
[WIP] Laravel Support

### ISSUE THREAD

**Issue by Alex-Bond** [spiral/roadrunner#96] opened 2019-01-17 12:25 UTC
Hi everyone!

After few usefull issues i figure out that Laravel integration is not so easy and have some hidden problems.
At this moment RoadRunner **DOES NO SUPPORT LARAVEL**!
Do not try to use proposed connector at any env.

I will keep everybody posted about progress and resolution of problem.

ETA: End of the week.

References: #60 #79 #91

**Comment by tectiv3** [comment] 2019-01-18 01:47
Do you need any help with that?

**Comment by Alex-Bond** [comment] 2019-01-18 07:10
@tectiv3 im ok for now. For me request-response is ok. The problem is in resenting objects.

**Comment by wolfy-j** [comment] 2019-01-24 21:59
Closed as stalled duplicate of #91

**Comment by Alex-Bond** [comment] 2019-01-25 04:08
I create beta version of new bridge - https://github.com/UPDG/roadrunner-laravel
@tectiv3 @Ostap34JS can you check that?

**Comment by tectiv3** [comment] 2019-01-25 10:50
it's alive! it's aliive!
yep, works perfect. Thank you :)

**Comment by wolfy-j** [comment] 2019-01-25 10:54
@Alex-Bond let me know when i can close other stories :)

**Comment by Alex-Bond** [comment] 2019-01-25 12:02
@wolfy-j i want to have at least 1 more confirmation from 3d side)

**Comment by barbushin** [comment] 2019-01-26 04:37
Guys, please take a loot at this solution https://github.com/swooletw/laravel-swoole/blob/master/config/swoole_http.php#L92-L120

Looks like to make roadrunner integration with Laravel to be most flexible and fast, it should implement same logics (service providers and instances restarters + cached instances sandbox).

Thank you!

**Comment by Alex-Bond** [comment] 2019-01-26 05:53
@barbushin wow. that a lot of reseters. I need to look into each of them.

**Closed** 2019-01-27 08:59 UTC
Labels: integration, need verification

**Comment by tarampampam** [comment] 2019-05-06 02:38
If some one looking for one more **RoadRunner ⇆ Laravel** bridge, take a look here:   https://github.com/avto-dev/roadrunner-laravel (MIT)

**Comment by Hunternnm** [comment] 2019-09-05 10:40
Another attempt to do integration) https://github.com/Hunternnm/laravel-roadrunner

Example https://github.com/Hunternnm/laravel-roadrunner-example
