### ISSUE TITLE
[BUG] Panic with the minimal config in README

### ISSUE THREAD

**Issue by shyim** [spiral/roadrunner#657] opened 2021-05-03 19:04 UTC
I tried this code:

```yaml
rpc:
    listen: tcp://127.0.0.1:6001

server:
    command: "php public/index.php"

http:
    address: "0.0.0.0:8080"

logs:
    level: error

```

I expected to see this happen: *explanation*
Working server at 8080

Instead, this happened: *explanation*

```
2021-05-03T19:03:17.040Z        ERROR   container/poller.go:16  vertex got an error     {"vertex id": "http.Plugin", "error": "http_plugin_serve: WorkerAllocate:\n\tserver_plugin_new_worker_pool:\n\tstatic_pool_initialize:\n\tallocate workers:\n\tfactory_spawn_worker_with_timeout: fetch_pid: CRC mismatch; signal: killed; process_wait: signal: killed"}
github.com/spiral/endure/pkg/container.(*Endure).poll.func1
        github.com/spiral/endure@v1.0.1/pkg/container/poller.go:16
error occurred: http_plugin_serve: WorkerAllocate:
        server_plugin_new_worker_pool:
        static_pool_initialize:
        allocate workers:
        factory_spawn_worker_with_timeout: fetch_pid: CRC mismatch; signal: killed; process_wait: signal: killed, plugin: http.Plugin
handle_serve_command: http_plugin_serve: WorkerAllocate:
        server_plugin_new_worker_pool:
        static_pool_initialize:
        allocate workers:
        factory_spawn_worker_with_timeout: fetch_pid: CRC mismatch; signal: killed; process_wait: signal: killed; fsm_recognizer: can't transition from state: Stopped by event Stop
```

The version of RR used: 2.1.1

Errortrace, Backtrace or Panictrace
```
<backtrace>
```

</p>
</details>

**Comment by 48d90782** [comment] 2021-05-03 19:50
Hey @shyim . Could you please share your `index.php` worker here? Because it seems, that this is some unexpected behavior in the worker.

**Comment by 48d90782** [comment] 2021-05-03 19:56
I tried to run our sample worker with your config sample and everything works well.
![image](https://user-images.githubusercontent.com/8040338/116926016-97e3e700-ac62-11eb-830d-74066b70e9be.png)
![image](https://user-images.githubusercontent.com/8040338/116926097-af22d480-ac62-11eb-9eca-49f6b602657e.png)
```php
<?php

declare(strict_types=1);

use Spiral\RoadRunner;
use Nyholm\Psr7\Factory;

ini_set('display_errors', 'stderr');
include "vendor/autoload.php";

$env = \Spiral\RoadRunner\Environment::fromGlobals();

if ($env->getMode() === 'http') {
    $worker = new RoadRunner\Http\PSR7Worker(
        RoadRunner\Worker::create(),
        new Factory\Psr17Factory(),
        new Factory\Psr17Factory(),
        new Factory\Psr17Factory()
    );

    while ($req = $worker->waitRequest()) {
        try {
            $rsp = new \Nyholm\Psr7\Response();
            $rsp->getBody()->write("hello world");
            $worker->respond($rsp);
        } catch (\Throwable $e) {
            $worker->getWorker()->error((string)$e);
        }
    }
} else {
    /**
     * @param string $dir
     * @return array<string>
     */
    $getClasses = static function (string $dir): iterable {
        $files = glob($dir . '/*.php');

        foreach ($files as $file) {
            yield substr(basename($file), 0, -4);
        }
    };

    $factory = \Temporal\WorkerFactory::create();

    $worker = $factory->newWorker('default');

    // register all workflows
    foreach ($getClasses(__DIR__ . '/src/Workflow') as $name) {
        $worker->registerWorkflowTypes('Temporal\\Tests\\Workflow\\' . $name);
    }

     // register all activity
    foreach ($getClasses(__DIR__ . '/src/Activity') as $name) {
        $class = 'Temporal\\Tests\\Activity\\' . $name;
        $worker->registerActivityImplementations(new $class);
    }

    $factory->run();
}
```

**Comment by 48d90782** [comment] 2021-05-03 19:57
The `else` branch is not needed here, only the first condition.

**Comment by shyim** [comment] 2021-05-03 21:35
Seems related to a nonexistent php file. The error handling seems very weak 🙈

**Comment by 48d90782** [comment] 2021-05-03 21:51
That's very hard to handle the error better because a command might be anything. Not only the path to the PHP script but other scripts like sh or Powershell. If the command would be limited for example: `php path/to/php` that would be easy to `stat` the php file and provide a good error message. But the command is not limited by only one case.
For sure, we will work to improve that case to have a better UX.

**Comment by 48d90782** [comment] 2021-05-04 09:01
@shyim The issue was caused by the wrong path?

**Comment by shyim** [comment] 2021-05-04 09:05
Yes the file didn't exist.

**Comment by 48d90782** [comment] 2021-05-04 09:22
Ok, I'm closing this issue since the problem was resolved.

**Closed by 48d90782** 2021-05-04 09:22 UTC
Labels: B-bug, F-need-verification
