### ISSUE TITLE
Zend\Diactoros\Exception\InvalidArgumentException: Invalid header value type; must be a string or numeric; received boolean

### ISSUE THREAD

**Issue by 4n70w4** [spiral/roadrunner#130] opened 2019-02-28 12:34 UTC
Setup from instruction: https://github.com/spiral/roadrunner/wiki/Symfony-Framework

Exception on each request:

```
Zend\Diactoros\Exception\InvalidArgumentException: Invalid header value type; must be a string or numeric; received boolean in /var/www/app/current/vendor/zendframework/zend-diactoros/src/HeaderSecurity.php:139
Stack trace:
#0 /var/www/app/current/vendor/zendframework/zend-diactoros/src/MessageTrait.php(398): Zend\Diactoros\HeaderSecurity::assertValid(true)
#1 [internal function]: Zend\Diactoros\Response->Zend\Diactoros\{closure}(true)
#2 /var/www/app/current/vendor/zendframework/zend-diactoros/src/MessageTrait.php(401): array_map(Object(Closure), Array)
#3 /var/www/app/current/vendor/zendframework/zend-diactoros/src/MessageTrait.php(338): Zend\Diactoros\Response->filterHeaderValue(Array)
#4 /var/www/app/current/vendor/zendframework/zend-diactoros/src/Response.php(134): Zend\Diactoros\Response->setHeaders(Array)
#5 /var/www/app/current/vendor/symfony/psr-http-message-bridge/Factory/DiactorosFactory.php(160): Zend\Diactoros\Response->__construct(Object(Zend\Diactoros\Stream), 200, Array)
#6 /var/www/app/current/worker.php(52): Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory->createResponse(Object(Symfony\Component\HttpFoundation\Response))
#7 {main}
```

**Comment by BunnyHolder** [comment] 2019-02-28 13:31
Today I had same problem, so I added debug and now waiting for bad headers, but because of some unknown reasons it does not reappear again. So maybe you could add this too.
```php
while ($request = $client->acceptRequest()) {
    $headers = [];
    try {
        $response = $httpServer->handlePSR7($request);
        $headers = $response->getHeaders();
        $client->respond($response);
        $httpServer->cleanup();
    } catch (\Zend\Diactoros\Exception\InvalidArgumentException $e) {
        $client->getWorker()->error("$e \n\n" . print_r($headers, true));
    } catch (\Throwable $e) {
        $client->getWorker()->error((string) $e);
    }
}
```

**Comment by 4n70w4** [comment] 2019-02-28 19:49
@BunnyHolder my app generated header:

`$h['Access-Control-Allow-Credentials'] = true;`

I add quotes and all work. It is strange that this library Zend\Diactoros does not accept the boolean header without quotes, because inside the symfony it all works correctly.

Perhaps there is a parameter in the Zend\Diactoros so that it does not throw out exceptions about it.

Perhaps need to create a issue in the Zend\Diactoros, or come up with a workaround and publish it in the instructions.

Because the current roadrunner symfony-example from the instructions is not fully compatible with the native symfony app.

**Comment by Alex-Bond** [comment] 2019-02-28 22:52
@4n70w4 hey. I didn't think of this case. I will fix it inside RR and my side module for SF.

**Comment by wolfy-j** [comment] 2019-03-01 07:29
You can use less strict PSR7 implementation instead.

**Comment by askobara** [comment] 2019-05-22 03:51
Same problem here:
` Invalid header value type; must be a string or numeric; received NULL`
It happens when browser try to send `access-control-allow-origin => NULL` (name of the header is not matter)

**Comment by wolfy-j** [comment] 2019-05-22 07:56
Hi, this is caused by the strict implementation of Zend Diactoros. If you have any issues using this library try to use alternative PSR-7 implementation. For example https://github.com/Nyholm/psr7 is fully compatible with RR and even provides greater performance. 

To enable alternative PSR-7 provides alter your PSR7Client constructor like that:

```php
$factory = new \Nyholm\Psr7\Factory\Psr17Factory();
$psr7 = new PSR7Client($worker, $factory, $factory, $factory);
```

In our synthetic benches it also provides +30% performance boost compared to Zend version.

**Comment by wolfy-j** [comment] 2019-06-24 11:07
Closing due to inability to bypass strict implementation of Zend. Use alternative PSR-7 implementations listed above.

**Closed by wolfy-j** 2019-06-24 11:07 UTC
Labels: integration, need verification
