### ISSUE TITLE
[BUG] Unable to install using composer

### ISSUE THREAD

**Issue by jwillp** [spiral/roadrunner#581] opened 2021-03-09 23:15 UTC
I tried installing the project using the composer method as outlined here: https://roadrunner.dev/docs/intro-install, in a fresh empty composer project, however, I get the following error:

```
PHP Fatal error:  Uncaught Error: Class 'Spiral\RoadRunner\Version' in ./vendor/spiral/roadrunner-cli/bin/rr:67
```

I tried this code:

```bash
composer require spiral/roadrunner
./vendor/bin/rr get
```
The version of RR used: ^2.0 (v2.0.1)

**Comment by SerafimArts** [comment] 2021-03-10 05:45
Hello @jwillp, thanks for feedback!

Can you please tell us the version of the `roadrunner-worker` you are using?

**Comment by jwillp** [comment] 2021-03-10 07:06
I did get to setup the worker.
I simply followed the documentation step about composer.

Here's what I did

```bash
$ composer init
$ composer require spiral/roadrunner
$ ./vendor/bin/rr get
```

I tried this on WSL, I will try again later on a native Linux machine.

**Comment by SerafimArts** [comment] 2021-03-10 08:29
@steffendietz Have you managed to reproduce this error on composer 1.x?

**Comment by SerafimArts** [comment] 2021-03-10 10:18
@steffendietz Yes, this is one of the solutions to the problem.

However, I am not sure that in this case the composer 1.x will not try to install a version that is compatible with it. That is, if we publish a new version `roadrunner 2.0.2` with a dependency on `roadrunner-worker ^2.0.1`, then it (composer 1.x) will try to install `roadrunner 2.0.1`. Because this is the most recent version satisfying all dependencies.

It seems to me that for a more reliable solution to the problem, we should re-release `roadrunner-worker 2.0.0`, adding a dependency on the `composer-runtime-api 2.x` there.

**Comment by jwillp** [comment] 2021-03-10 14:09
@SerafimArts @steffendietz 
I can confirm that the machine I was having trouble with was on composer 1.x, good catch!

After upgrading and reinstalling the dependencies, I was able to complete the installation.
Thanks for the support.

**Comment by SerafimArts** [comment] 2021-03-10 15:21
The dependencies in the 2.0.0 tag were corrected, now this problem should not arise: https://packagist.org/packages/spiral/roadrunner-worker#v2.0.0

**Comment by 48d90782** [comment] 2021-03-11 05:59
@jwillp Feel free to close the issue if the problem was resolved.

**Closed** 2021-03-11 07:25 UTC
Labels: B-bug
