### ISSUE TITLE
Add RoadRunner to brew.sh

### ISSUE THREAD

**Issue by jasonmccallister** [spiral/roadrunner#603] opened 2021-03-18 17:18 UTC
**Is your feature request related to a problem? Please describe.**
It would be amazing to have RoadRunner installable through brew.sh. We use GoReleaser.com to build the tap required for macOS users to run `brew install roadrunner`. 

**Describe the solution you'd like**
Adding RoadRunner as a Brew Tap. We have an example of using GoReleaser to publish to brew here: https://github.com/craftcms/nitro/blob/main/.goreleaser.yml

**Describe alternatives you've considered**
We can use `go get` to install, but having a "production" binary ready with Brew would be 👌.

**Comment by 48d90782** [comment] 2021-03-18 17:26
Hey @jasonmccallister , nice to meet you. We already have the ticket for this request. If you don't mind, could you please move your thoughts as a comment to the #397. Thanks.
duplicate of the #397

**Closed by 48d90782** 2021-03-18 17:26 UTC
Labels: C-feature-request, F-duplicate
