### ISSUE TITLE
Can't get raw content if wrong Content-Type header

### ISSUE THREAD

**Issue by speller** [spiral/roadrunner#123] opened 2019-02-16 09:55 UTC
Hi,
In my application it sometimes receive POST requests with JSON body but with the `application/x-www-form-urlencoded` content type. The script doesn't rely on $_POST or its equivalents, but just need to get the raw request content. But RR tries to convert request content to a form data and sends broken data to PHP. How can I get raw content even with a wrong header?

**Comment by wolfy-j** [comment] 2019-02-16 10:03
I am not seeing any clear option rather than changing content-type to the correct value. Passing raw content is possible but it will double the package size without any real benefit except cases like that. RoadRunner won't parse request and send it as binary stream if content-type set correctly.

**Comment by speller** [comment] 2019-02-16 10:17
I can't see significant issue with doubling data sent to PHP. Very big forms are seen very rare. The issue can be when we are posting files, but when posting files raw content is not accessible in classic PHP, so it will not be an issue in RR if following this rule. What if to add an option to pass raw post data always except files?

**Comment by Alex-Bond** [comment] 2019-02-18 05:13
This issue can be addressed in the next major version by changing the package format a little bit. We can add configuration for that in order to save the size of the package.
I dont think it will slow down system at all.

**Comment by wolfy-j** [comment] 2019-06-14 09:48
I'm closing this issue, we might implement it in 2.0 version but so far it looks like the overhead caused by improperly configured request.

**Closed by wolfy-j** 2019-06-14 09:48 UTC
Labels: magic, question
